; Firmware SENTINEL-X — ESP8266 NodeMCU Lolin v3 (ESP-12E)
; Compiler : pio run        Flasher : pio run -t upload       Moniteur : pio device monitor
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Port série : à renseigner si la détection automatique échoue (fiche EPSI)
; upload_port = COM5
; monitor_port = COM5
board_build.f_cpu = 80000000L
build_flags =
  -D BUILD_EPOCH=$UNIX_TIME
  -D MQTT_MAX_PACKET_SIZE=512
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0
  adafruit/DHT sensor library@^1.4
  adafruit/Adafruit Unified Sensor@^1.1
  adafruit/Adafruit SSD1306@^2.5
  adafruit/Adafruit GFX Library@^1.11

; Banc d'essai sans Wi-Fi : pio run -e bench -t upload   (ou make bench-upload)
[env:bench]
extends = env:esp12e
build_flags = ${env:esp12e.build_flags} -D BENCH_NO_WIFI
